"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { format, parseISO } from "date-fns"
import { ChevronRight, Package, ShoppingBag } from "lucide-react"
import { getSupabaseClient } from "@/lib/supabase"
import { AccountShell } from "@/components/account/account-shell"
import { MobileAccountNav } from "@/components/account/account-sidebar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

type Order = { id:string; total_amount:number; status:string; created_at:string; order_items:any; businesses?:{business_name:string;slug:string}|null }
const statusClass=(s:string)=>["delivered","completed"].includes(s)?"bg-emerald-100 text-emerald-700":s==="cancelled"?"bg-red-100 text-red-700":"bg-purple-100 text-purple-700"
export default function OrdersPage(){const router=useRouter();const [loading,setLoading]=useState(true);const [orders,setOrders]=useState<Order[]>([]);useEffect(()=>{(async()=>{const s=getSupabaseClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace("/auth/login?next=/account/orders");return}const {data}=await s.from("orders").select("id,total_amount,status,created_at,order_items,businesses(business_name,slug)").eq("customer_id",user.id).order("created_at",{ascending:false});setOrders((data as Order[])||[]);setLoading(false)})()},[router]);return <AccountShell><main className="mx-auto max-w-5xl px-5 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-8 flex items-center gap-3"><MobileAccountNav/><div><p className="text-sm text-muted-foreground">Personal account</p><h1 className="text-3xl font-bold">My orders</h1></div></header>{loading?<p className="text-muted-foreground">Loading orders...</p>:orders.length===0?<Empty/>:<div className="space-y-4">{orders.map(o=>{const items=Array.isArray(o.order_items)?o.order_items:[];const names=items.map((i:any)=>i.product_name||i.name).filter(Boolean).join(", ");return <Card key={o.id} className="shadow-sm"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-purple-100 text-purple-700"><Package className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="font-semibold">{o.businesses?.business_name||"Zentry business"}</p><p className="mt-1 truncate text-sm text-muted-foreground">{names||"Order placed through Zentry"}</p><p className="mt-2 text-xs text-muted-foreground">{format(parseISO(o.created_at),"MMM d, yyyy · h:mm a")}</p></div><div className="flex items-center justify-between gap-5 sm:block sm:text-right"><div><Badge className={statusClass(o.status)}>{o.status.replaceAll("_"," ")}</Badge><p className="mt-2 font-semibold">${Number(o.total_amount||0).toFixed(2)}</p></div><Button variant="ghost" size="sm" className="mt-1" asChild><Link href={o.businesses?.slug?`/b/${o.businesses.slug}`:"/marketplace"}>View <ChevronRight className="ml-1 h-4 w-4"/></Link></Button></div></CardContent></Card>})}</div>}</main></AccountShell>}
function Empty(){return <Card className="border-dashed"><CardContent className="flex flex-col items-center py-20 text-center"><div className="rounded-2xl bg-purple-100 p-4 text-purple-700"><ShoppingBag className="h-7 w-7"/></div><h2 className="mt-5 text-xl font-semibold">Nothing ordered yet</h2><p className="mt-2 text-sm text-muted-foreground">When you place an order, its live status will appear here.</p><Button asChild className="mt-5 rounded-xl"><Link href="/marketplace">Explore marketplace</Link></Button></CardContent></Card>}
